spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myschelin?serverTimezone=Asia/Seoul
    username: root
    password: 


  servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 25MB

  devtools:
    remote:
      restart:
        enabled: true

  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"